# Generated by Django 4.0 on 2023-07-18 04:28

from django.db import migrations, models
import django_resized.forms
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Album_Title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='memberpic',
            field=models.ManyToManyField(blank=True, related_name='artwork_post', to='artwork.ArtworkPost'),
        ),
        migrations.AlterField(
            model_name='artworkpost',
            name='Artwork',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='media/img/'),
        ),
        migrations.AlterField(
            model_name='artworkpost',
            name='Title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=1, force_format=None, keep_meta=True, quality=-1, scale=None, size=[180, 180], upload_to='media/img/profile_pic'),
            preserve_default=False,
        ),
    ]
