# Generated by Django 4.0 on 2023-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artworkpost_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkpost',
            name='imageUploader',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/'),
        ),
    ]
