# Generated by Django 4.0 on 2023-07-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
