# Generated by Django 4.0 on 2023-07-02 13:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_profile_facebook_profile_instagram_profile_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=1, force_format=None, keep_meta=True, quality=-1, scale=None, size=[180, 180], upload_to='media/img/profile_pic'),
            preserve_default=False,
        ),
    ]
