# Generated by Django 4.0 on 2023-04-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('artwork', '0004_albumartist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumArtist',
            new_name='Album',
        ),
    ]
