# Generated by Django 4.0 on 2023-07-26 06:04

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='media/img/profile_pic'),
        ),
    ]
