# Generated by Django 4.0 on 2023-07-02 15:05

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkpost',
            name='Artwork',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='media/img/'),
        ),
    ]
