# Generated by Django 4.0 on 2023-07-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_alter_artworkpost_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='memberpic',
            field=models.ManyToManyField(blank=True, related_name='artwork_post', to='artwork.ArtworkPost'),
        ),
    ]
