# Generated by Django 4.0 on 2023-07-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('artwork', '0006_collection_alter_album_memberpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='albumlist',
            field=models.ManyToManyField(blank=True, related_name='album', to='artwork.ArtworkPost'),
        ),
        migrations.AddField(
            model_name='collection',
            name='coluser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
