# Generated by Django 4.0 on 2023-04-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Title',
            new_name='Album_Title',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='CoverPhoto',
            new_name='Cover_Photo',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artistName',
            new_name='artist_Name',
        ),
        migrations.RenameField(
            model_name='artworkpost',
            old_name='artistName',
            new_name='artist_Name',
        ),
    ]
