# Generated by Django 4.0 on 2023-04-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_alter_album_cover_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Facebook',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Instagram',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Twitter',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/profile_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_media',
            field=models.TextField(),
        ),
    ]
