# Generated by Django 4.0 on 2023-04-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0010_profile_facebook_profile_instagram_profile_twitter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_media',
            new_name='bio',
        ),
    ]
