# Generated by Django 4.0 on 2023-05-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0012_albumdatabase_artworkdatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumDatabase',
        ),
        migrations.DeleteModel(
            name='ArtWorkDatabase',
        ),
    ]
