# Generated by Django 4.0 on 2023-05-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0013_delete_albumdatabase_delete_artworkdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artworkpost',
            name='Tag',
        ),
        migrations.AddField(
            model_name='artworkpost',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='artworkpost', to='artwork.Tag'),
        ),
    ]
