# Generated by Django 4.0 on 2023-06-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0016_remove_album_cover_photo_remove_album_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Private_Album',
            field=models.BooleanField(default=False),
        ),
    ]
