# Generated by Django 4.0 on 2023-06-17 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0017_album_private_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.AddField(
            model_name='artworkpost',
            name='likes',
            field=models.ManyToManyField(related_name='artwork_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
