# Generated by Django 4.0 on 2023-06-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0018_delete_carousel_artworkpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkpost',
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
