# Generated by Django 4.0 on 2023-06-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0020_artworkpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkpost',
            name='album',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artworkpost',
            name='Artwork',
            field=models.FileField(blank=True, default=1, upload_to='media/img/'),
            preserve_default=False,
        ),
    ]
