# Generated by Django 4.0 on 2023-06-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0022_alter_comment_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkpost',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='memberpic',
            field=models.ManyToManyField(related_name='artwork_post', to='artwork.ArtworkPost'),
        ),
    ]
